---
- name: RedHat | Set loaded_os_family
  set_fact:
    loaded_os_family: "{{ ansible_os_family }}"

- name: RedHat | Add the New Relic repository
  yum:
    name: https://yum.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm
    state: present

- name: RedHat | Install New Relic Sysmond
  yum:
    name: newrelic-sysmond
    state: latest
  notify: Restart New Relic
